# Site settings
title: 啦啦啦 我叫野山鸡
SEOTitle: 野山鸡的博客 | BY Blog
header-img: img/ceshi/TIM 123.jpg
email: 3342667396@qq.com
description: "hey"
keyword: "BY, 野山鸡, 野山鸡的博客, yeshanji,"
url: "http://yeshanji.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/yeshanji/yeshanji.github.io" # you code repository
